# Product

GET https://logical-fort-425301-p0.uc.r.appspot.com/products
###

GET https://logical-fort-425301-p0.uc.r.appspot.com/products/search?value=coca
###


# Sales

GET https://logical-fort-425301-p0.uc.r.appspot.com/sales/search?date=2024-06-01
###

GET https://logical-fort-425301-p0.uc.r.appspot.com/sales/report?start-date=2024-06-01&end-date=2024-06-03
###

POST https://logical-fort-425301-p0.uc.r.appspot.com/sales
Content-Type: application/json

{
  "product_id": "85de6b28-a553-4c15-81e7-eacc72e74c88",
  "customer_name": "Sara",
  "quantity_sold": 2
}